### ISSUE TITLE
The background of file picker windows, and some settings pages are not translucent

### ISSUE THREAD

**Issue by skylineone044** [Davide-sd/FlatBlur#1]
See images:
![Screenshot_20191006_184433](https://user-images.githubusercontent.com/37515608/66272493-c2917200-e86a-11e9-9cae-8f9e15270f90.png)
![Screenshot_20191006_185253](https://user-images.githubusercontent.com/37515608/66272497-c91fe980-e86a-11e9-851f-509576cdd716.png)

This one is good, for reference:
![Screenshot_20191006_185334](https://user-images.githubusercontent.com/37515608/66272499-ccb37080-e86a-11e9-918b-41e912df238f.png)

**Comment by Davide-sd** [comment]
I believe this is KDE mess!!! They are not consistent in the UI development, as you can see from your last screenshot. The colors used in those windows are based on the Color Scheme settings. Why are they doing that is way out my comprehension.

BTW: nice background, love the Roci too! :)

**Comment by skylineone044** [comment]
I see...
Then they are screwing it up on an unpresidented level, as I just discovered the file select window on kvantum-manager is  perfectly translucent

![Screenshot_20191006_193206](https://user-images.githubusercontent.com/37515608/66273006-4306a180-e870-11e9-980e-f62f91e78c9d.png)

**Comment by Davide-sd** [comment]
Regarding vlc (and maybe some other application you use).

Open Kvantum Manager -> Configure Active Theme -> Compositing and General Look -> Opaque Apps. Look into this text edit, find vlc and delete it! Then vlc file browser should use transparency.

Please, understand that I have not tested whether this will cause any other part of the application to behave in a strange way...

**Comment by skylineone044** [comment]
Alright, that did it for the file selection window, and other parts of it look fine.
Now I guess it's just waiting for the KDE guys to fix up the system settings.
Whenever that happens.
