### ISSUE TITLE
Half the rows in Dolphin's detailed view are not transparent

### ISSUE THREAD

**Issue by skylineone044** [Davide-sd/FlatBlur#2]
They are #292c2f, and not transparent:
![Screenshot_20191007_163308](https://user-images.githubusercontent.com/37515608/66323407-0eecb880-e924-11e9-8e17-f72bbf9b157d.png)
whereas in the screenshot in the README.md they are

**Comment by Davide-sd** [comment]
Did you compiled and installed the [lastest Kvantum manager](https://github.com/tsujan/Kvantum/tree/master/Kvantum)?

**Comment by skylineone044** [comment]
Did that, now it works, thanks.
Although it should be more clearly communicated.
Also, I thought I already had a recent enough version (I'm running manjaro), but apparently I was not.

**Comment by Davide-sd** [comment]
Really, it was very well written as requirements both in the Pling page as well as here on Github...

**Comment by skylineone044** [comment]
Yeah now I see it, it was the middle of the night and I was tired so I missed it
but it's fine now, my bad
